name: Build

on:
  push:
    branches: [ master, development ]
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
    - name: download mikeros tools
      uses: arma-actions/mikero-tools@latest
    - name: Install deps
      run: npm i
    - name: Build
      run: npm run buildAndPack
    - name: Zip Artifacts
      run: zip -r -j server-manager.zip build/*
    - name: Archive build artifacts
      if: "!startsWith(github.ref, 'refs/tags/v')"
      uses: actions/upload-artifact@v3
      with:
        name: server-manager.zip
        path: ./server-manager.zip
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      id: create_release
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: ${{ github.ref }}
        name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      if: startsWith(github.ref, 'refs/tags/v')
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./server-manager.zip
        asset_name: server-manager.zip
        asset_content_type: application/zip
